/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#151d1e',
        'secondary-container': '#af8d11',
        'on-primary-container': '#00626e',
        'on-secondary': '#3c2f00',
        'surface-bright': '#333a3c',
        'obsidian': '#0B0D11',
        'inverse-on-surface': '#2a3233',
        'on-error-container': '#ffdad6',
        'on-tertiary-container': '#6f5500',
        'surface-container': '#192122',
        'tertiary-fixed-dim': '#f3bf26',
        'surface-container-highest': '#2e3638',
        'true-black': '#000000',
        'on-tertiary': '#3e2e00',
        'primary': '#c3f5ff',
        'inverse-surface': '#dce4e5',
        'on-background': '#dce4e5',
        'secondary-fixed': '#ffe088',
        'on-primary': '#00363d',
        'on-tertiary-fixed': '#251a00',
        'surface-dim': '#0d1516',
        'outline-variant': '#3b494c',
        'on-surface-variant': '#bac9cc',
        'tertiary-container': '#fec931',
        'on-secondary-container': '#342800',
        'deep-navy': '#0A192F',
        'surface-variant': '#2e3638',
        'background': '#0d1516',
        'surface-container-high': '#242b2d',
        'primary-fixed-dim': '#00daf3',
        'on-error': '#690005',
        'on-primary-fixed-variant': '#004f58',
        'inverse-primary': '#006875',
        'surface': '#0d1516',
        'on-surface': '#dce4e5',
        'tertiary-fixed': '#ffdf96',
        'on-primary-fixed': '#001f24',
        'secondary-fixed-dim': '#e9c349',
        'primary-container': '#00e5ff',
        'surface-tint': '#00daf3',
        'error': '#ffb4ab',
        'silver-metallic': '#C0C0C8',
        'tertiary': '#ffeac0',
        'secondary': '#e9c349',
        'error-container': '#93000a',
        'outline': '#849396',
        'primary-fixed': '#9cf0ff',
        'on-secondary-fixed': '#241a00',
        'cyan-glow': 'rgba(0, 229, 255, 0.4)',
        'surface-container-lowest': '#080f11',
      },
      borderRadius: {
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'gutter': '24px',
        'bento-gap': '12px',
        'margin-mobile': '20px',
        'unit': '4px',
        'margin-desktop': '80px',
      },
      fontFamily: {
        'sora': ['Sora', 'sans-serif'],
        'geist': ['Geist', 'sans-serif'],
        'jetbrains': ['JetBrains Mono', 'monospace'],
        'display-hero': ['Sora', 'sans-serif'],
        'headline-lg': ['Sora', 'sans-serif'],
        'headline-lg-mobile': ['Sora', 'sans-serif'],
        'headline-md': ['Sora', 'sans-serif'],
        'body-lg': ['Geist', 'sans-serif'],
        'body-md': ['Geist', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'utility-mono': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-hero': ['72px', { lineHeight: '80px', letterSpacing: '-0.04em', fontWeight: '800' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '500' }],
        'utility-mono': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
